const about = [
	"coded this website",
	"doesn’t have time for this",
	"has a lot of stuff to do",
	"plays the saxophone",
	"makes games",
	"makes music",
	"makes things",
	"writes stories",
	"writes code",
	"is a boyish girl making games about girly boys",
	"is a girly boy writing stories about boyish girls",
	"is a rogue wall enthusiast",
	"is a fan of wet circles",
	"is a rainbow aficionado",
	"is a false prophet",
	"is a figment",
	"is a dweeb",
	"is a long series of increasingly worse decisions",
	"is just a dreamer",
	"wants to be everything at once",
	"watches the watchmen",
	"is constantly feigning disinterest",
	"is loading, please wait…",
	"is my name and making games is my game",
	"is not here right now. Can I take a message?",
	"is procrastinating",
	"is probably playing Tetris right now",
	"is probably reading comics right now",
	"is probably watching anime right now",
	"is probably watching Netflix right now",
	"is probably just thinking about stuff and things right now",
	"is probably sleeping right now",
	"is probably not sleeping right now",
	"should be sleeping",
	"is tired",
	"is trying",
	"is awkward",
	"is your best nightmare",
	"once stayed in bed for six hours after waking up"
];
